### ISSUE TITLE
TypeError: device is undefined  /  Extension initialising...

### ISSUE THREAD

**Issue by spielkind** [kgshank/gse-sound-output-device-chooser#134]
**Describe the bug**
I often (for example after a standby)  just see "Extension initialising...." 
![image](https://user-images.githubusercontent.com/4437264/105969503-9ebdf500-6088-11eb-9020-d07feeb85364.png)

**Extension Information**
OS: Arch Linux
Gnome Shell: 1:3.38.3-1
Extension Version: 34
Install method: GIT

**Error / Journal messages**
```
Jan 27 10:10:19 xxxxxx gnome-shell[1773]: JS ERROR: TypeError: device is undefined
                                          _setDeviceActiveProfile@/home/yyyyyy/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/base.js:374:13
                                          _setActiveProfile@/home/yyyyyyyy/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/base.js:369:14
Jan 27 10:10:19 xxxxxxxxx gnome-shell[1773]: JS ERROR: TypeError: device is undefined
                                          _setDeviceActiveProfile@/home/yyyyyyyyy/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/base.js:374:13
                                          _setActiveProfile@/home/yyyyyyyyyy/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/base.js:369:14
```

**Comment by kgshank** [comment]
@spielkind Please reinstall from Git again. The trace does not match the source in Git. Also, I have pushed additional checks now to avoid crashes

**Comment by spielkind** [comment]
Updated again from git, after a while I again got the "Extension initializing..."
![image](https://user-images.githubusercontent.com/4437264/106126770-1ad63c80-615e-11eb-9a46-03e8259a6d2a.png)

The "Output Device"  (Bose QC 35 II via Bluetooth) I currently use is now missing in the extension list.
 Can't find any log entries, so the logs before were may not related to.

Disabling/Enabling Extension won't "fix" the issue. Instead a full gnome shell restart (ALT+F2 -> "r") does.
![image](https://user-images.githubusercontent.com/4437264/106127371-cbdcd700-615e-11eb-9f71-494c33199f60.png)

But still no logs at all. :/

Hardware I use:
- Lenovo ThinkPad X280
- Lenovo USB-C Dock (which also have Audio, which I don't use)
- Bose QC35II Bluetooth Headset

**Comment by kgshank** [comment]
For some reason, the device is added to the list.

Enable Log messages in the extension settings

and share the messages from these commands
`journalctl -r | grep SDC | more`

This one will give messages if the extension is not initialized
`journalctl -r | grep sound | more`

If both of them dont work, post the last lines from related to gnome shell
`journalctl -r | more`

**Comment by spielkind** [comment]
![image](https://user-images.githubusercontent.com/4437264/106191121-bdb4a800-61aa-11eb-8060-fc06fda02187.png)

[sdc-debug.log](https://github.com/kgshank/gse-sound-output-device-chooser/files/5889672/sdc-debug.log)

**Comment by kgshank** [comment]
@spielkind, Please try again from the git. I have committed some changes based on your log

**Comment by spielkind** [comment]
Still have issues.
[sdc-debug-new.log](https://github.com/kgshank/gse-sound-output-device-chooser/files/5914160/sdc-debug-new.log)

Also had the problem that the laptop didn't woke up from suspend (no useful logs for this) - but this is probably not related.
Another strange thing is: when I remove the extension and try to switch output devices through gnome sound settings this doesn't work at all for my bluetooth headset.

**Comment by kgshank** [comment]
I had similar issues with bluetooth headsets in the past. Its mainly related to the pulseaudio not recognizing the profiles for some reason. Try restarting pulseaudio and it should work again

**Comment by artscoop** [comment]
I've discovered that downgrading to the release from mid January works fine. (Gnome 3.38.3)
The last release of the plugin, and code from every recent commit breaks the plugin with an "Extension initialising..." message for both input and output devices.

**Comment by Scotty-Trees** [comment]
Don't know if this'll help at all, but I'd just like to mention something in my testing since I experience this "initializing error" as well. I'm on PopOS! 20.04, Gnome 3.36.8, using v34 of this extension. 

I noticed when I use my bluetooth UE Boom 2, if I leave it on and lock my laptop, after about 15 mins of inactive use (ie not playing any music/podcast), the UE Boom shuts down to save battery. If I do this, when I log back in, I don't seem to have the issue. Normally though I don't want to leave the UE Boom ON when I lock my laptop so I usually turn it OFF before I lock my laptop. However, if I power down the UE Boom BEFORE I lock my laptop, and then lock my laptop and then unlock it at any time later, then I get the extension initializing error that's been happening lately. So it seems it's not registering or re-registering something maybe, sorry if that's not much help. 

I hope I was able to explain enough to make sense and hope it may help any little bit perhaps! Good luck fixing the issue, I'm sure y'all will fix it :)

**Comment by lyoshenka** [comment]
I also have this issue. Anything I can provide that would help debugging?


Device: Bose QC35 II
OS: Ubuntu 20.04
Gnome Shell: 3.36.4
Extension Version: 34
Install method: unzip release into `.local/share/...`

**Comment by andrebrait** [comment]
I also have it

OS: Ubuntu 20.04
Extension version: 34
Install method: from the GNOME extensions website

**Comment by fortizc** [comment]
Same issue here with a very similar HW configuration than @spielkind
* ThinkPad L480 (1 audio device)
* QC35 II (1 audio device)
* Revolve SoundLink (3 audio devices, Bluetooth, analog, and S/PDIF)
One more audio device is added with the HDMI monitor.

On the SW side, my configuration is pretty standard
Ubuntu 20.04
Gnome 3.36.8
Extension version 34

**Comment by dmusican** [comment]
Ditto for me as well. I've got exactly the same configuration as @fortizc.

**Comment by Basskrapfen** [comment]
Same issue here, Ubuntu 20.10 on a Lenovo ThinkPad.

It especially happens when resuming from standby. What seems to work is to restart the Gnome Shell as a workaround (ALT+F2: "r"), after this the device chooser is shown correctly.

**Comment by c1p0** [comment]
Having the same issue on a very similar setup.
Thinkpad T480s
Thinkpad TB Dock
Edifier W830BT headphones
Ubuntu 20.10
Gnome 3.38.3

It seems the issue has stared happening for me after I got the BT headphones. 
It happens after coming back from sleep. 

Restarting Gnome with Alt+F2 then "r" fixes this issue. 

Let me know if there are any other details that might help you get to the bottom of this.

**Comment by PaulVanSchayck** [comment]
I'm getting the same. Also more likely to occur after resuming from suspend or after connecting to docking station. I can fix it by restarting pulseaudio (`pulseaudio -k`) and/or restarting gnome-shell (ALT+F2 + r). Pop!OS 20.10, using a Thinkpad X1. 

I see the following lines in journalctl:
```
mrt 07 13:56:20 thinkpad-pvs gnome-shell[4657]: #2   7ffd2ee09760 b   self-hosted:850 (2d9016f1a510 @ 398)
mrt 07 13:56:20 thinkpad-pvs gnome-shell[4657]: #1   7ffd2ee096a0 b   /home/paul/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/base.js:373 (3e861e876a0 @ 45)
mrt 07 13:56:20 thinkpad-pvs gnome-shell[4657]: #0   55cd6a1924b8 i   /home/paul/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/base.js:386 (3e861e87650 @ 154)
mrt 07 13:56:20 thinkpad-pvs gnome-shell[4657]: == Stack trace for context 0x55cd66e26220 ==
mrt 07 13:56:20 thinkpad-pvs gnome-shell[4657]: Bail out! Gvc:ERROR:../subprojects/gvc/gvc-mixer-card.c:166:gvc_mixer_card_get_profile: code should not be reached
mrt 07 13:56:20 thinkpad-pvs gnome-shell[4657]: Gvc:ERROR:../subprojects/gvc/gvc-mixer-card.c:166:gvc_mixer_card_get_profile: code should not be reached
mrt 07 13:56:19 thinkpad-pvs gnome-shell[4657]: Sync_devices: Failed to match stream id: 34, description: 'Digital Microphone', origin: 'Cannon Point-LP High Definition Audio Controller Digital Microphone'
mrt 07 13:56:19 thinkpad-pvs gnome-shell[4657]: Sync_devices: Failed to match stream id: 33, description: 'Headphones Stereo Microphone', origin: 'Cannon Point-LP High Definition Audio Controller Headphones Stereo Microphone'
mrt 07 13:56:19 thinkpad-pvs gnome-shell[4657]: gvc_mixer_ui_device_get_id: assertion 'GVC_IS_MIXER_UI_DEVICE (device)' failed
mrt 07 13:56:19 thinkpad-pvs gnome-shell[4657]: Sync_devices: Failed to match stream id: 32, description: 'Headset Microphone', origin: 'HyperX 7.1 Audio Analog Stereo'
mrt 07 13:56:19 thinkpad-pvs gnome-shell[4657]: Sync_devices: Failed to match stream id: 30, description: 'Headphones', origin: 'Cannon Point-LP High Definition Audio Controller Speaker + Headphones'
mrt 07 13:56:19 thinkpad-pvs gnome-shell[4657]: Sync_devices: Failed to match stream id: 30, description: 'Speaker', origin: 'Cannon Point-LP High Definition Audio Controller Speaker + Headphones'
mrt 07 13:56:19 thinkpad-pvs gnome-shell[4657]: Sync_devices: Failed to match stream id: 29, description: 'HDMI1/DP1 Output', origin: 'Cannon Point-LP High Definition Audio Controller HDMI1/DP1 Output'
mrt 07 13:56:19 thinkpad-pvs gnome-shell[4657]: Sync_devices: Failed to match stream id: 28, description: 'HDMI2/DP2 Output', origin: 'Cannon Point-LP High Definition Audio Controller HDMI2/DP2 Output'
mrt 07 13:56:19 thinkpad-pvs gnome-shell[4657]: Sync_devices: Failed to match stream id: 27, description: 'HDMI3/DP3 Output', origin: 'Cannon Point-LP High Definition Audio Controller HDMI3/DP3 Output'
mrt 07 13:56:19 thinkpad-pvs gnome-shell[4657]: gvc_mixer_ui_device_get_id: assertion 'GVC_IS_MIXER_UI_DEVICE (device)' failed
mrt 07 13:56:19 thinkpad-pvs gnome-shell[4657]: Sync_devices: Failed to match stream id: 26, description: 'Analog Output', origin: 'HyperX 7.1 Audio Analog Stereo'
```

Not sure it's related. This was without the debug option enabled in the extension. Will start paying more attention.

Also issue #142 may be related.

**Comment by AJJLagerweij** [comment]
I have the same issues, mostly with my Bluetooth headset. Most of the time the initialization message goes away when I turn off my headset. If I then turn on the headset it auto-connects,  and the extension works without problems. Until it doesn't anymore after quite some time.
I have not figured out the trigger for the initialization problem yet, but it might be caused by putting and waking my laptop from sleep, possibly in combination with me turning my headset off just before or during the hibernation of my laptop.

**Comment by theseer** [comment]
I'm also running into this issue, but with a slightly(?) different hardware setup:

- Thinkpad X1
- Logitech H800 Wireless Headset connected via its USB fob (that is *not* using Bluetooth)
- The USB Fob is plugged into a OneLink+
- Thinkpad connected via OnlineLink+ Cable

Pulling the USB fob, reinserting it and then just re-connecting the headset seems to "Fix" it.

This makes me wonder whether or not this is actually an issue with this extension or its just suffering under a lower level issue?

**Comment by kgshank** [comment]
If possible test with the git version and let me know if this issue still occurs

**Comment by PaulVanSchayck** [comment]
Thanks. I'll be testing over the next few days and I'll report back

**Comment by dmusican** [comment]
Same for me, I have installed it and I will try it for a few days. Thanks!

**Comment by andrebrait** [comment]
So far so good. Only downside is that the different profiles for Bluetooth devices (the A2DP sinks and HSP profile) don't show up anymore.

Before I could switch between then on a drop-down menu below the bluetooth device and I can't do it anymore.

**Comment by dmusican** [comment]
Agreed. So far it is stable and always showing consistent results. Thank you!

@andrebrait: did you double check the extension settings, and make sure those devices weren't selected as "hide" under port settings? I had that problem with one of my devices. (I honestly can't remember now if I had manually selected that at some point in the past or not, guess I probably did but I'm unsure.)

**Comment by andrebrait** [comment]
> Agreed. So far it is stable and always showing consistent results. Thank you!
> 
> @andrebrait: did you double check the extension settings, and make sure those devices weren't selected as "hide" under port settings? I had that problem with one of my devices. (I honestly can't remember now if I had manually selected that at some point in the past or not, guess I probably did but I'm unsure.)

Yes, I checked that. The device is visible and it's not hidden in the settings. Only the profiles don't show up.

**Comment by AJJLagerweij** [comment]
@kgshank I've had great experience the last couple of days. No issues at all, awesome.

@andrebrait I can see the sound profiles, as shown below, but can not see my Bluetooth profiles, even though I can select those from my sound settings menu:
![afbeelding](https://user-images.githubusercontent.com/31255888/112105432-74d30b80-8bbd-11eb-9fb0-bf8e83833f6c.png)

**Comment by andrebrait** [comment]
@AJJLagerweij precisely what I'm experiencing

**Comment by Kerwood** [comment]
I tried to install the update but it failed. If I reinstall i will get an error. Not sure how to debug or which logs to look in.

![image](https://user-images.githubusercontent.com/4029521/112314048-d91ec980-8ca8-11eb-9666-62c76a26960e.png)

**Comment by kgshank** [comment]
@andrebrait  @AJJLagerweij  Git has fixes for missing bluetooth profiles. 

@Kerwood  this is a problem with extensions.gnome.org, log out /log in should fix the issue

**Comment by Kerwood** [comment]
> @Kerwood this is a problem with extensions.gnome.org, log out /log in should fix the issue

I didn't login to start with. Anyway, I created an account and it still fails.

**Comment by theseer** [comment]
> > @Kerwood this is a problem with extensions.gnome.org, log out /log in should fix the issue
> 
> I didn't login to start with. Anyway, I created an account and it still fails.
> I can install other extentions.

You have to re-login to gnome, not the extensions site. It's a (wayland?) related problem with gnome and extensions.gnome.org when updating (!) an extension. Just relogin (or restart the gnome shell in case you still have x11: alt-f2, r)

**Comment by AJJLagerweij** [comment]
@theseer the issue describe is not limited to wayland, my x11 has the same issue. To ensure that the installation is correct I take the following steps
1. Install update or new extension on [gnome.org](https://extensions.gnome.org/extension/906/sound-output-device-chooser/)
2. It errors out
3. Relaunch the gnome shell, as you said by shortcut `alt-f2` and running `r`
4. Refresh the gnome.org to verify that the installation went correct (`f5`), or open the [installed extensions page](https://extensions.gnome.org/local/).

**Comment by theseer** [comment]
@AJJLagerweij Thanks for the clarification. Since the error started showing up for me at the same time when I switched to Wayland, I wasn't sure whether that was related. So for me and as a reference to everybody else who might read this, on Wayland, Step 3 would be a re-login to the gnome desktop. The rest is the same.

**Comment by Kerwood** [comment]
> You have to re-login to gnome, not the extensions site. It's a (wayland?) related problem with gnome and extensions.gnome.org when updating (!) an extension. Just relogin (or restart the gnome shell in case you still have x11: alt-f2, r)

Of course.. Im an idiot sandwich. Thanks you.

**Comment by andrebrait** [comment]
@kgshank bug is back. Worked fine in 03a9cd3e1c6d54e30e05454381ef3285117bafc0m but it's broken again in V37.

**Comment by ainar** [comment]
I experienced this bug after updating to the latest version on gnome.org, but the bug disappeared after reinstallation.

**Comment by laichiaheng** [comment]
The git version in AUR causes this problem, but the release version solves this problem.
