### ISSUE TITLE
Error: Extension not enable

### ISSUE THREAD

**Issue by AdsonCicilioti** [kgshank/gse-sound-output-device-chooser#52]
![image](https://user-images.githubusercontent.com/6278398/52066296-66e64a80-255f-11e9-953b-9330b844ac80.png)

GNOME 3.30.2
Fedora 29
```
GLib.SpawnError: Falha ao executar processo filho “pactl” (No such file or directory)

Stack trace:
  refreshCards@/home/adson/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/convenience.js:103:41
  getPorts@/home/adson/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/convenience.js:95:9
  _populatePorts@/home/adson/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/prefs.js:114:21
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _init@/home/adson/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/prefs.js:108:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  buildPrefsWidget@/home/adson/.local/share/gnome-shell/extensions/sound-output-device-chooser@kgshank.net/prefs.js:208:27
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:83:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:235:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:389:5
  @<main>:1:43
```

**Comment by BjoernDaase** [comment]
I can confirm this problem in 3.31.90.

**Comment by silviobierman** [comment]
For what it's worth: I have the same problem on 3.31.90 in Ubuntu Disco Dingo (19.04 dev branch).

**Comment by lathiat** [comment]
This issue is hitting a lot of extensions with gnome-shell 3.32.

The best conversation about how to fix this that I can find is in dash-to-dock, where they already fixed it with a merged PR:
https://github.com/micheleg/dash-to-dock/pull/881

**Comment by lathiat** [comment]
Looks like this was fixed by #53, seems not yet released to the store

**Comment by kgshank** [comment]
Pushed #53 to gnome extensions, but other issues are still not fixed.

**Comment by kgshank** [comment]
Please check with the new version and comment if the issue still appears

**Comment by AdsonCicilioti** [comment]
@kgshank Thanks Very much!
I've test and works fine for me!

Fedora 30 - Gnome 3.32
